auto doSomething(auto a,auto b){writeln(sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){writeln(Math.sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){console.log(sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){console.log(Math.sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){writeln(sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){writeln(Math.sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){console.log(sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){console.log(Math.sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){writeln(sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){writeln(Math.sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){console.log(sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){console.log(Math.sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){writeln(sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){writeln(Math.sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){console.log(sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){console.log(Math.sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){writeln(sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){writeln(Math.sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){console.log(sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){console.log(Math.sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){writeln(sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){writeln(Math.sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){console.log(sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){console.log(Math.sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){writeln(sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){writeln(Math.sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){console.log(sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){console.log(Math.sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){writeln(sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){writeln(Math.sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){console.log(sin(a));
auto q=a/b;
return a+b;},auto doSomething(auto a,auto b){console.log(Math.sin(a));
auto q=a/b;
return a+b;}